// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      //case TargetPlatform.iOS:
        //return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1Eima8xlw6LuS_zNNrA8ND6hzTKULCZA',
    appId: '1:718146572376:web:c38e437cd22f40eaf37a2d',
    messagingSenderId: '718146572376',
    projectId: 'vocab-trainer-eng',
    authDomain: 'vocab-trainer-eng.firebaseapp.com',
    storageBucket: 'vocab-trainer-eng.firebasestorage.app',
  );

   static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1Eima8xlw6LuS_zNNrA8ND6hzTKULCZA',
    appId: '1:718146572376:android:c38e437cd22f40eaf37a2d',
    messagingSenderId: '718146572376',
    projectId: 'vocab-trainer-eng',
    storageBucket: 'vocab-trainer-eng.firebasestorage.app',
  );
  
  /*static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4hXJHB8RW_UYXvTvuejulJt6f4YFQe3o',
    appId: '1:925203969606:web:574b18845e37c2ac74bc47',
    messagingSenderId: '925203969606',
    projectId: 'tms-quiz',
    authDomain: 'tms-quiz.firebaseapp.com',
    storageBucket: 'tms-quiz.appspot.com',
  );*/

   
  /*static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeEGcxvDnewPNanFNvfQgFRmcNt6ocyi4',
    appId: '1:925203969606:android:4c717ca7dfc3490574bc47',
    messagingSenderId: '925203969606',
    projectId: 'tms-quiz',
    storageBucket: 'tms-quiz.appspot.com',
  );*/

  /*static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGVhjULCyD7v4nnMmUSKo2i_t1la5Ip90',
    appId: '1:925203969606:ios:0604b83f30638fb774bc47',
    messagingSenderId: '925203969606',
    projectId: 'tms-quiz',
    storageBucket: 'tms-quiz.appspot.com',
    iosClientId: '925203969606-4l477eqr1otlrdc8h8u7p230govre4b3.apps.googleusercontent.com',
    iosBundleId: 'com.tms.flutter.quiz.tmsQuiz',
  );  */
}


/*
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1Eima8xlw6LuS_zNNrA8ND6hzTKULCZA',
    appId: '1:718146572376:web:c38e437cd22f40eaf37a2d',
    messagingSenderId: '718146572376',
    projectId: 'vocab-trainer-eng',
    authDomain: 'vocab-trainer-eng.firebaseapp.com',
    storageBucket: 'tocab-trainer-eng.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1Eima8xlw6LuS_zNNrA8ND6hzTKULCZA',
    appId: '1:718146572376:web:c38e437cd22f40eaf37a2d',
    messagingSenderId: '718146572376',
    projectId: 'vocab-trainer-eng',
    storageBucket: 'vocab-trainer-eng.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1Eima8xlw6LuS_zNNrA8ND6hzTKULCZA',
    appId: '1:718146572376:ios:0604b83f30638fb774bc47',
    messagingSenderId: '718146572376',
    projectId: 'vocab-trainer-eng',
    storageBucket: 'vocab-trainer-eng.firebasestorage.app',
    iosClientId: '718146572376-4l477eqr1otlrdc8h8u7p230govre4b3.apps.googleusercontent.com',
    iosBundleId: 'com.tms.flutter.quiz.tmsQuiz',
  );




const firebaseConfig = {
  apiKey: "AIzaSyD1Eima8xlw6LuS_zNNrA8ND6hzTKULCZA",
  authDomain: "vocab-trainer-eng.firebaseapp.com",
  projectId: "vocab-trainer-eng",
  storageBucket:  "vocab-trainer-eng.firebasestorage.app",
  messagingSenderId: "718146572376",
  appId: "1:718146572376:web:c38e437cd22f40eaf37a2d",
  measurementId:  "G-L43ZTX8M86"
};
*/